/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:dd3fed4d-d712-440a-af16-b16bf5b9c2ef",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_DQpPM15TX",
    "aws_user_pools_web_client_id": "4evk2m4ru8rrenij1ukg0044k6",
    "oauth": {},
    "aws_cloud_logic_custom": [
        {
            "name": "finopsAgentAPI",
            "endpoint": "${API_GATEWAY_ENDPOINT}",
            "region": "us-east-1"
        }
    ]
};

export default awsmobile;
