AWSTemplateFormatVersion: '2010-09-09'
Description: 'CloudFormation template for AWS Cost Analysis and Forecasting Agent Lambda function with Bedrock access, Provisioned Concurrency, and Alias support'

Parameters:
  AppS3Key:
    Type: String
    Default: app.zip
    Description: S3 key for the Lambda application code
    
  DependenciesS3Key:
    Type: String
    Default: dependencies.zip
    Description: S3 key for the Lambda dependencies layer
    
  LambdaTimeout:
    Type: Number
    Default: 300
    Description: Lambda function timeout in seconds
    
  LambdaMemorySize:
    Type: Number
    Default: 512
    Description: Lambda function memory size in MB
    
  ProvisionedConcurrency:
    Type: Number
    Default: 2
    Description: Number of provisioned concurrent executions

Resources:
  CostForecastAgentRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: '*'
              - Effect: Allow
                Action:
                  - ce:GetCostAndUsage
                  - ce:GetCostForecast
                  - ce:GetReservationUtilization
                  - ce:GetSavingsPlansUtilization
                  - ce:GetDimensionValues
                  - ce:GetTags
                  - ce:GetUsageForecast
                  - ce:GetSavingsPlansUtilizationDetails
                  - ce:GetReservationUtilizationDetails
                  - ce:GetCostCategories
                  - ce:ListCostCategoryDefinitions
                Resource: '*'
  
  CostForecastAgentDependenciesLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: aws-cost-forecast-agent-dependencies
      Description: Dependencies for AWS Cost Analysis and Forecasting Agent
      Content:
        S3Bucket: finops-deployment-packages-062025
        S3Key: !Ref DependenciesS3Key
      CompatibleRuntimes:
        - python3.10
        - python3.11
        - python3.12
      
  CostForecastAgentLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: aws-cost-forecast-agent
      Description: AWS Cost Analysis and Forecasting Agent powered by Strands SDK with Bedrock integration
      Runtime: python3.11
      Handler: lambda_handler.handler
      Role: !GetAtt CostForecastAgentRole.Arn
      Code:
        S3Bucket: finops-deployment-packages-062025
        S3Key: !Ref AppS3Key
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemorySize
      Layers:
        - !Ref CostForecastAgentDependenciesLayer
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          LOG_LEVEL: INFO
          STRANDS_MODEL_REGION: !Ref AWS::Region
          STRANDS_MODEL_ID: anthropic.claude-3-5-haiku-20241022-v1:0
          
  # Lambda Version - Creates a snapshot of the current function
  CostForecastAgentVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !Ref CostForecastAgentLambda
      Description: !Sub "Version deployed on ${AWS::StackName}"
      
  # Lambda Alias - Points to the version and enables provisioned concurrency
  CostForecastAgentAlias:
    Type: AWS::Lambda::Alias
    Properties:
      FunctionName: !Ref CostForecastAgentLambda
      FunctionVersion: !GetAtt CostForecastAgentVersion.Version
      Name: PROD
      Description: "Production alias for cost forecast agent with provisioned concurrency"
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: !Ref ProvisionedConcurrency
          
  CostForecastAgentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub "/aws/lambda/${CostForecastAgentLambda}"
      RetentionInDays: 30

Outputs:
  LambdaFunction:
    Description: AWS Cost Analysis and Forecasting Agent Lambda Function
    Value: !Ref CostForecastAgentLambda
    
  LambdaFunctionArn:
    Description: AWS Cost Analysis and Forecasting Agent Lambda Function ARN
    Value: !GetAtt CostForecastAgentLambda.Arn
    
  LambdaAliasArn:
    Description: AWS Cost Analysis and Forecasting Agent Production Alias ARN
    Value: !Ref CostForecastAgentAlias
    Export:
      Name: !Sub "${AWS::StackName}-CostForecastAgentAliasArn"
    
  LambdaVersion:
    Description: AWS Cost Analysis and Forecasting Agent Version
    Value: !GetAtt CostForecastAgentVersion.Version
    
  DependenciesLayer:
    Description: AWS Cost Analysis and Forecasting Agent Dependencies Layer
    Value: !Ref CostForecastAgentDependenciesLayer
    
  ProvisionedConcurrency:
    Description: Number of provisioned concurrent executions
    Value: !Ref ProvisionedConcurrency
