AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Cost Forecast Agent - Serverless cost analysis and forecasting with Strands SDK'

Parameters:
  DeploymentBucket:
    Type: String
    Description: S3 bucket name for deployment artifacts
    MinLength: 3
    MaxLength: 63
    AllowedPattern: '^[a-z0-9][a-z0-9-]*[a-z0-9]$'
    ConstraintDescription: Must be a valid S3 bucket name
    
  AppS3Key:
    Type: String
    Default: aws-cost-forecast-agent/app.zip
    Description: S3 key for the Lambda application code
    
  DependenciesS3Key:
    Type: String
    Default: aws-cost-forecast-agent/dependencies.zip
    Description: S3 key for the Lambda dependencies layer
    
  LambdaTimeout:
    Type: Number
    Default: 300
    MinValue: 30
    MaxValue: 900
    Description: Lambda function timeout in seconds (30-900)
    
  LambdaMemorySize:
    Type: Number
    Default: 512
    MinValue: 128
    MaxValue: 10240
    Description: Lambda function memory size in MB (128-10240)
    
  LogRetentionDays:
    Type: Number
    Default: 30
    AllowedValues: [1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653]
    Description: CloudWatch log retention period in days
    
  Environment:
    Type: String
    Default: prod
    AllowedValues: [dev, staging, prod]
    Description: Deployment environment

Resources:
  # IAM Role for Cost Forecast Agent Lambda
  CostForecastAgentRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub 'finops-cost-forecast-agent-role-${Environment}'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: CostExplorerAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ce:GetCostAndUsage
                  - ce:GetCostForecast
                  - ce:GetReservationUtilization
                  - ce:GetSavingsPlansUtilization
                  - ce:GetDimensionValues
                  - ce:GetTags
                  - ce:GetUsageForecast
                  - ce:GetSavingsPlansUtilizationDetails
                  - ce:GetReservationUtilizationDetails
                  - ce:GetCostCategories
                  - ce:ListCostCategoryDefinitions
                Resource: '*'
        - PolicyName: BedrockAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - bedrock:InvokeModel
                  - bedrock:InvokeModelWithResponseStream
                Resource: 
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/*'
                  - !Sub 'arn:aws:bedrock:${AWS::Region}:${AWS::AccountId}:model/*'
      Tags:
        - Key: Project
          Value: FinOpsAgent
        - Key: Component
          Value: CostForecastAgent
        - Key: Environment
          Value: !Ref Environment

  # Lambda Layer for Dependencies
  CostForecastAgentDependenciesLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      LayerName: !Sub 'finops-cost-forecast-agent-deps-${Environment}'
      Description: Dependencies for AWS Cost Forecast Agent (Strands SDK, boto3)
      Content:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Ref DependenciesS3Key
      CompatibleRuntimes:
        - python3.11
        - python3.12
      CompatibleArchitectures:
        - x86_64
        - arm64

  # Lambda Function
  CostForecastAgentLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub 'finops-cost-forecast-agent-${Environment}'
      Description: AWS Cost Analysis and Forecasting Agent powered by Strands SDK
      Runtime: python3.11
      Handler: lambda_handler.handler
      Role: !GetAtt CostForecastAgentRole.Arn
      Code:
        S3Bucket: !Ref DeploymentBucket
        S3Key: !Ref AppS3Key
      Timeout: !Ref LambdaTimeout
      MemorySize: !Ref LambdaMemorySize
      Layers:
        - !Ref CostForecastAgentDependenciesLayer
      Environment:
        Variables:
          REGION: !Ref AWS::Region
          LOG_LEVEL: INFO
          ENVIRONMENT: !Ref Environment
          POWERTOOLS_SERVICE_NAME: cost-forecast-agent
          POWERTOOLS_METRICS_NAMESPACE: FinOpsAgent
      ReservedConcurrencyLimit: 10
      DeadLetterQueue:
        TargetArn: !GetAtt CostForecastAgentDLQ.Arn
      Tags:
        - Key: Project
          Value: FinOpsAgent
        - Key: Component
          Value: CostForecastAgent
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Log Group
  CostForecastAgentLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub '/aws/lambda/finops-cost-forecast-agent-${Environment}'
      RetentionInDays: !Ref LogRetentionDays
      Tags:
        - Key: Project
          Value: FinOpsAgent
        - Key: Component
          Value: CostForecastAgent
        - Key: Environment
          Value: !Ref Environment

  # Dead Letter Queue for failed invocations
  CostForecastAgentDLQ:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub 'finops-cost-forecast-agent-dlq-${Environment}'
      MessageRetentionPeriod: 1209600  # 14 days
      Tags:
        - Key: Project
          Value: FinOpsAgent
        - Key: Component
          Value: CostForecastAgent
        - Key: Environment
          Value: !Ref Environment

  # CloudWatch Alarms
  CostForecastAgentErrorAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'finops-cost-forecast-agent-errors-${Environment}'
      AlarmDescription: Monitor errors in Cost Forecast Agent
      MetricName: Errors
      Namespace: AWS/Lambda
      Statistic: Sum
      Period: 300
      EvaluationPeriods: 2
      Threshold: 5
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref CostForecastAgentLambda
      TreatMissingData: notBreaching

  CostForecastAgentDurationAlarm:
    Type: AWS::CloudWatch::Alarm
    Properties:
      AlarmName: !Sub 'finops-cost-forecast-agent-duration-${Environment}'
      AlarmDescription: Monitor duration of Cost Forecast Agent
      MetricName: Duration
      Namespace: AWS/Lambda
      Statistic: Average
      Period: 300
      EvaluationPeriods: 2
      Threshold: !Ref LambdaTimeout
      ComparisonOperator: GreaterThanOrEqualToThreshold
      Dimensions:
        - Name: FunctionName
          Value: !Ref CostForecastAgentLambda
      TreatMissingData: notBreaching

Outputs:
  LambdaFunctionName:
    Description: Cost Forecast Agent Lambda Function Name
    Value: !Ref CostForecastAgentLambda
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionName'
    
  LambdaFunctionArn:
    Description: Cost Forecast Agent Lambda Function ARN
    Value: !GetAtt CostForecastAgentLambda.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaFunctionArn'
    
  LambdaRoleArn:
    Description: Cost Forecast Agent Lambda Role ARN
    Value: !GetAtt CostForecastAgentRole.Arn
    Export:
      Name: !Sub '${AWS::StackName}-LambdaRoleArn'
    
  DependenciesLayerArn:
    Description: Cost Forecast Agent Dependencies Layer ARN
    Value: !Ref CostForecastAgentDependenciesLayer
    Export:
      Name: !Sub '${AWS::StackName}-DependenciesLayerArn'
      
  LogGroupName:
    Description: CloudWatch Log Group Name
    Value: !Ref CostForecastAgentLogGroup
    Export:
      Name: !Sub '${AWS::StackName}-LogGroupName'
